# Generated by Django 5.0.13 on 2025-04-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('World', 'World'), ('Business', 'Business'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment')], default='General', max_length=100),
        ),
    ]
