# Generated by Django 5.0.13 on 2025-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_trending_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_articles', models.BooleanField(default=False)),
                ('auto_approve_images', models.BooleanField(default=False)),
                ('auto_approve_videos', models.BooleanField(default=False)),
                ('site_offline_mode', models.BooleanField(default=False)),
                ('default_category', models.CharField(default='General', max_length=50)),
                ('enable_article_generation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='aiimage',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiimage',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aivideo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aivideo',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
