# Generated by Django 5.1 on 2025-04-07 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_category_aiimage_aivideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='aivideo',
            name='article',
        ),
        migrations.AddField(
            model_name='aiimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ai_images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aivideo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aivideo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aivideo',
            name='video',
            field=models.FileField(max_length=500, upload_to='ai_videos/'),
        ),
    ]
