# Generated by Django 5.0.13 on 2025-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_aiimage_article_remove_aivideo_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
