# Generated by Django 5.1 on 2025-04-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Tech', 'Tech'), ('World', 'World'), ('Business', 'Business'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment')], default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='AIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_images/')),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_image', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='AIVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='ai_videos/')),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_video', to='articles.article')),
            ],
        ),
    ]
